version: "3"
services:

  postgres:
    container_name: postgres_chart
    image: postgres:latest
    environment:
      POSTGRES_DB: 'chart'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - chart_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: 'unless-stopped'
    networks:
      - postgres

  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@habr.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports: 
      - 5050:80
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres
      
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    volumes:
      - ./migrations:/app/sql
    environment:
      FLYWAY_CONNECT_RETRIES: 60
      FLYWAY_LOCATIONS: filesystem:/app/sql
      FLYWAY_SCHEMAS: trading
    command: -url=jdbc:postgresql://postgres/chart -user=user -password=password -connectRetries=60 migrate
    depends_on:
      - postgres
    networks:
      - postgres
  
